"""
solana_client.py
================

Async client for the polis on-chain programs, driven by anchorpy + the IDLs
generated by `anchor build`.

All instruction encoding (discriminator + borsh args), account decoding, and
event parsing flow through `anchorpy.Program` and `anchorpy.EventParser`. This
module is responsible for:

* Loading the IDLs and instantiating one ``Program`` per polis program.
* Deriving PDAs (seeds documented inline; verified against the IDL `pda.seeds`).
* Building + submitting instructions on behalf of the agent operator.
* Reading account state (`CreditLine`, `VouchPool`, `Wallet`, `RepStats`).
* Subscribing to the x402 program logs and decoding `PaymentReceived` events
  into a local payment cache used by `/summarize`.

The public surface (`register_agent`, `pay_for_service`, `transfer_out_wallet`,
`deposit_to_pool`, ..., `vouch`, `unvouch_request`, `slash`) is the same as
the pre-IDL revision so the rest of the agent (treasury_manager.py,
credit_manager.py, server.py) is unchanged.
"""
from __future__ import annotations

import asyncio
import contextlib
import dataclasses
import logging
import os
import time
from pathlib import Path
from typing import Any, Optional

from anchorpy import Context, EventParser, Program, Provider, Wallet
from anchorpy.program.namespace.account import AccountClient
from solders.hash import Hash
from solders.instruction import Instruction
from solders.keypair import Keypair
from solders.message import MessageV0
from solders.pubkey import Pubkey
from solders.transaction import VersionedTransaction

from solana.rpc.async_api import AsyncClient
from solana.rpc.commitment import Confirmed
from solana.rpc.types import TxOpts

from idls import IDL_NAMES, load_idls

# Well-known program addresses we pass into account lists.
SYSTEM_PROGRAM_ID = Pubkey.from_string("11111111111111111111111111111111")
TOKEN_PROGRAM_ID = Pubkey.from_string("TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA")
ASSOCIATED_TOKEN_PROGRAM_ID = Pubkey.from_string(
    "ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL"
)
SYSVAR_RENT_ID = Pubkey.from_string("SysvarRent111111111111111111111111111111111")

log = logging.getLogger(__name__)


# ---------- USDC base units --------------------------------------------------

USDC_DECIMALS = 6
USDC_BASE = 10 ** USDC_DECIMALS


def usd_to_base(value: float) -> int:
    return int(round(value * USDC_BASE))


def base_to_usd(value: int) -> float:
    return value / USDC_BASE


# ---------- Payment cache ----------------------------------------------------


@dataclasses.dataclass
class PaymentRecord:
    payment_id: str
    payer: str
    amount: int  # USDC base units
    memo: Optional[str]
    timestamp: float  # unix seconds, observed locally


# ---------- Program-ID configuration ----------------------------------------


@dataclasses.dataclass
class ProgramIds:
    identity: Pubkey
    wallet: Pubkey
    x402: Pubkey
    credit: Pubkey
    reputation: Pubkey

    @classmethod
    def from_env(cls) -> "ProgramIds":
        return cls(
            identity=Pubkey.from_string(os.environ["POLIS_IDENTITY_PROGRAM_ID"]),
            wallet=Pubkey.from_string(os.environ["POLIS_WALLET_PROGRAM_ID"]),
            x402=Pubkey.from_string(os.environ["POLIS_X402_PROGRAM_ID"]),
            credit=Pubkey.from_string(os.environ["POLIS_CREDIT_PROGRAM_ID"]),
            reputation=Pubkey.from_string(os.environ["POLIS_REPUTATION_PROGRAM_ID"]),
        )


# ---------- ATA derivation ---------------------------------------------------


def derive_ata(owner: Pubkey, mint: Pubkey) -> Pubkey:
    """Derive the associated token account address for (owner, mint).

    Equivalent to `getAssociatedTokenAddress(mint, owner, allowOwnerOffCurve=true)`
    in @solana/spl-token. PDA seeds: (owner, TOKEN_PROGRAM_ID, mint).
    """
    addr, _bump = Pubkey.find_program_address(
        [bytes(owner), bytes(TOKEN_PROGRAM_ID), bytes(mint)],
        ASSOCIATED_TOKEN_PROGRAM_ID,
    )
    return addr


# ---------- Client ----------------------------------------------------------


class SolanaClient:
    """Async client for the polis programs.

    Holds: operator keypair, RPC/WS connections, the agent's code-hash, a
    payment cache for /summarize verification, and one ``Program`` per polis
    program (loaded from the JSON IDLs emitted by `anchor build`).
    """

    def __init__(
        self,
        rpc_url: str,
        operator_keypair_path: str,
        usdc_mint: Pubkey,
        code_hash: bytes,
        program_ids: ProgramIds,
        payment_validity_seconds: int = 300,
    ) -> None:
        assert len(code_hash) == 32, "code_hash must be 32 bytes"
        self.rpc_url = rpc_url
        self.ws_url = _derive_ws_url(rpc_url)
        self.code_hash = code_hash
        self.usdc_mint = usdc_mint
        self.programs = program_ids
        self.payment_validity_seconds = payment_validity_seconds

        self.operator = _load_keypair(operator_keypair_path)
        self._client = AsyncClient(rpc_url, commitment=Confirmed)

        # anchorpy provider, used by Program instances for account fetching.
        self._provider = Provider(
            connection=self._client,
            wallet=Wallet(self.operator),
            opts=TxOpts(
                skip_preflight=False,
                preflight_commitment=Confirmed,
                skip_confirmation=False,
            ),
        )

        # Load every IDL and bind to its program ID.
        idls = load_idls()
        program_id_lookup = {
            "identity": program_ids.identity,
            "wallet": program_ids.wallet,
            "x402": program_ids.x402,
            "credit": program_ids.credit,
            "reputation": program_ids.reputation,
        }
        self.programs_by_name: dict[str, Program] = {
            name: Program(idls[name], program_id_lookup[name], self._provider)
            for name in IDL_NAMES
        }

        # Bound x402 event parser used by the log subscriber.
        self._x402_event_parser = EventParser(
            program_ids.x402, self.programs_by_name["x402"].coder
        )

        # payment_id -> PaymentRecord
        self._payment_cache: dict[str, PaymentRecord] = {}
        self._cache_lock = asyncio.Lock()
        self._ws_task: Optional[asyncio.Task[None]] = None

    # ----- shorthand accessors ---------------------------------------------

    @property
    def identity_program(self) -> Program:
        return self.programs_by_name["identity"]

    @property
    def wallet_program(self) -> Program:
        return self.programs_by_name["wallet"]

    @property
    def x402_program(self) -> Program:
        return self.programs_by_name["x402"]

    @property
    def credit_program(self) -> Program:
        return self.programs_by_name["credit"]

    @property
    def reputation_program(self) -> Program:
        return self.programs_by_name["reputation"]

    # ----- lifecycle --------------------------------------------------------

    async def close(self) -> None:
        if self._ws_task is not None:
            self._ws_task.cancel()
            with contextlib.suppress(asyncio.CancelledError):
                await self._ws_task
        # Close all Program instances + the underlying RPC client.
        for program in self.programs_by_name.values():
            with contextlib.suppress(Exception):
                await program.close()
        await self._client.close()

    # ----- PDA derivation ---------------------------------------------------
    #
    # Seeds match the `pda.seeds` declarations in the IDLs (verified against
    # the on-chain programs in programs/<name>/src/lib.rs).

    def agent_pda(self) -> tuple[Pubkey, int]:
        return Pubkey.find_program_address(
            [b"agent", self.code_hash], self.programs.identity
        )

    def stake_bond_pda(self) -> tuple[Pubkey, int]:
        return Pubkey.find_program_address(
            [b"stake", self.code_hash], self.programs.identity
        )

    def wallet_pda(self) -> tuple[Pubkey, int]:
        return Pubkey.find_program_address(
            [b"wallet", self.code_hash], self.programs.wallet
        )

    def credit_line_pda(self) -> tuple[Pubkey, int]:
        return Pubkey.find_program_address(
            [b"credit", self.code_hash], self.programs.credit
        )

    def vouch_pool_pda(self) -> tuple[Pubkey, int]:
        return Pubkey.find_program_address(
            [b"vouch", self.code_hash], self.programs.reputation
        )

    def rep_stats_pda(self) -> tuple[Pubkey, int]:
        return Pubkey.find_program_address([b"rep_stats"], self.programs.reputation)

    def pool_pda(self) -> tuple[Pubkey, int]:
        return Pubkey.find_program_address([b"pool"], self.programs.credit)

    def voucher_pda(self, staker: Pubkey, code_hash: Optional[bytes] = None) -> tuple[Pubkey, int]:
        ch = code_hash if code_hash is not None else self.code_hash
        return Pubkey.find_program_address(
            [b"voucher", ch, bytes(staker)], self.programs.reputation
        )

    # ----- chain helpers ----------------------------------------------------

    async def latest_blockhash(self) -> Hash:
        resp = await self._client.get_latest_blockhash()
        return resp.value.blockhash

    async def send_instruction(self, ix: Instruction) -> str:
        """Sign with operator and submit one instruction. Returns tx signature."""
        bh = await self.latest_blockhash()
        msg = MessageV0.try_compile(
            payer=self.operator.pubkey(),
            instructions=[ix],
            address_lookup_table_accounts=[],
            recent_blockhash=bh,
        )
        tx = VersionedTransaction(msg, [self.operator])
        resp = await self._client.send_raw_transaction(
            bytes(tx),
            opts=TxOpts(skip_preflight=False, preflight_commitment=Confirmed),
        )
        sig = str(resp.value)
        log.info("submitted tx %s", sig)
        return sig

    async def get_wallet_usdc_balance(self) -> int:
        """Read the Wallet PDA's USDC token account balance, in base units."""
        wallet, _ = self.wallet_pda()
        try:
            resp = await self._client.get_token_accounts_by_owner_json_parsed(
                wallet,
                {"mint": self.usdc_mint},
                commitment=Confirmed,
            )
        except Exception as exc:
            log.warning("get_token_accounts_by_owner failed: %s", exc)
            return 0
        for account in resp.value:
            parsed = account.account.data.parsed
            try:
                amount = int(parsed["info"]["tokenAmount"]["amount"])
                return amount
            except (KeyError, TypeError, ValueError):
                continue
        return 0

    # ----- instruction-level builders --------------------------------------
    #
    # Each helper returns a built `Instruction` so the caller can compose
    # several in one tx if desired. They use anchorpy's `program.instruction`
    # namespace which handles discriminator + borsh arg serialisation from
    # the IDL.

    def ix_transfer_out(self, destination_ata: Pubkey, amount: int) -> Instruction:
        """Wallet.transfer_out — moves USDC from Wallet PDA to a destination ATA.

        The wallet program enforces is_paused + per_trade_cap_bps internally.
        The operator key signs as `caller`; the SPL token CPI is signed by
        the Wallet PDA, not by the operator.
        """
        wallet_pda, _ = self.wallet_pda()
        wallet_ata = derive_ata(wallet_pda, self.usdc_mint)
        return self.wallet_program.instruction["transfer_out"](
            amount,
            destination_ata,
            ctx=Context(
                accounts={
                    "wallet": wallet_pda,
                    "usdc_mint": self.usdc_mint,
                    "wallet_ata": wallet_ata,
                    "destination_ata": destination_ata,
                    "caller": self.operator.pubkey(),
                    "token_program": TOKEN_PROGRAM_ID,
                },
            ),
        )

    def ix_credit_borrow(self, amount: int) -> Instruction:
        """Credit.borrow — opens / updates the agent's CreditLine for `amount`."""
        wallet_pda, _ = self.wallet_pda()
        credit_line, _ = self.credit_line_pda()
        pool, _ = self.pool_pda()
        vouch_pool, _ = self.vouch_pool_pda()
        rep_stats, _ = self.rep_stats_pda()
        pool_usdc = derive_ata(pool, self.usdc_mint)
        agent_wallet_usdc = derive_ata(wallet_pda, self.usdc_mint)
        return self.credit_program.instruction["borrow"](
            bytes(self.code_hash),
            amount,
            wallet_pda,
            ctx=Context(
                accounts={
                    "pool": pool,
                    "credit_line": credit_line,
                    "vouch_pool": vouch_pool,
                    "rep_stats": rep_stats,
                    "pool_usdc": pool_usdc,
                    "agent_wallet_usdc": agent_wallet_usdc,
                    "caller": self.operator.pubkey(),
                    "usdc_mint": self.usdc_mint,
                    "token_program": TOKEN_PROGRAM_ID,
                    "system_program": SYSTEM_PROGRAM_ID,
                },
            ),
        )

    def ix_credit_repay(self, amount: int) -> Instruction:
        """Credit.repay — pays down the agent's CreditLine.

        The signer (`payer`) pays from their own USDC ATA. In the agent loop
        the operator pays from its personal ATA. The credit program internally
        CPIs into reputation::distribute_voucher_yield for the 30% voucher cut.
        """
        credit_line, _ = self.credit_line_pda()
        pool, _ = self.pool_pda()
        vouch_pool, _ = self.vouch_pool_pda()
        rep_stats, _ = self.rep_stats_pda()
        pool_usdc = derive_ata(pool, self.usdc_mint)
        vouch_pool_usdc = derive_ata(vouch_pool, self.usdc_mint)
        payer_usdc = derive_ata(self.operator.pubkey(), self.usdc_mint)
        return self.credit_program.instruction["repay"](
            bytes(self.code_hash),
            amount,
            ctx=Context(
                accounts={
                    "pool": pool,
                    "credit_line": credit_line,
                    "vouch_pool": vouch_pool,
                    "vouch_pool_usdc": vouch_pool_usdc,
                    "rep_stats": rep_stats,
                    "payer": self.operator.pubkey(),
                    "payer_usdc": payer_usdc,
                    "pool_usdc": pool_usdc,
                    "usdc_mint": self.usdc_mint,
                    "token_program": TOKEN_PROGRAM_ID,
                    "reputation_program": self.programs.reputation,
                },
            ),
        )

    def ix_credit_accrue(self) -> Instruction:
        """Credit.accrue — pure interest update. No fund movement."""
        credit_line, _ = self.credit_line_pda()
        return self.credit_program.instruction["accrue"](
            bytes(self.code_hash),
            ctx=Context(accounts={"credit_line": credit_line}),
        )

    # ----- higher-level methods (used by managers + server) ---------------
    #
    # These are convenience wrappers that build + submit in one call. The
    # async/await flow lets us await the signature.

    async def transfer_out_wallet(self, destination_ata: Pubkey, amount: int) -> str:
        """Build + submit a wallet.transfer_out. Returns tx signature."""
        return await self.send_instruction(self.ix_transfer_out(destination_ata, amount))

    async def borrow_credit(self, amount: int) -> str:
        return await self.send_instruction(self.ix_credit_borrow(amount))

    async def repay_credit(self, amount: int) -> str:
        return await self.send_instruction(self.ix_credit_repay(amount))

    async def accrue_credit(self) -> str:
        return await self.send_instruction(self.ix_credit_accrue())

    async def register_agent(self, bond_amount: int) -> str:
        """Identity.register_agent — one-time agent registration with stake bond.

        The operator signs and funds. The bond is escrowed in a PDA-owned ATA.
        The operator's own USDC ATA must hold ≥ bond_amount before calling.
        """
        agent_pda, _ = self.agent_pda()
        stake_bond, _ = self.stake_bond_pda()
        operator_usdc = derive_ata(self.operator.pubkey(), self.usdc_mint)
        stake_bond_usdc = derive_ata(stake_bond, self.usdc_mint)
        ix = self.identity_program.instruction["register_agent"](
            bytes(self.code_hash),
            self.operator.pubkey(),
            bond_amount,
            ctx=Context(
                accounts={
                    "operator": self.operator.pubkey(),
                    "agent_profile": agent_pda,
                    "stake_bond": stake_bond,
                    "usdc_mint": self.usdc_mint,
                    "operator_usdc": operator_usdc,
                    "stake_bond_usdc": stake_bond_usdc,
                    "system_program": SYSTEM_PROGRAM_ID,
                    "token_program": TOKEN_PROGRAM_ID,
                    "associated_token_program": ASSOCIATED_TOKEN_PROGRAM_ID,
                    "rent": SYSVAR_RENT_ID,
                },
            ),
        )
        return await self.send_instruction(ix)

    async def pay_for_service(
        self,
        agent_code_hash: bytes,
        amount: int,
        memo: Optional[str] = None,
    ) -> str:
        """X402.pay_for_service — pays a polis agent for one service call.

        The agent's wallet PDA is re-derived inside the program from
        ``agent_code_hash``, so the destination cannot be spoofed at the
        caller's discretion.
        """
        # The agent being paid is not necessarily *this* agent; the caller
        # specifies which code_hash to credit. Default: own code_hash.
        target_wallet_pda, _ = Pubkey.find_program_address(
            [b"wallet", agent_code_hash], self.programs.wallet
        )
        agent_wallet_ata = derive_ata(target_wallet_pda, self.usdc_mint)
        payer_ata = derive_ata(self.operator.pubkey(), self.usdc_mint)
        ix = self.x402_program.instruction["pay_for_service"](
            bytes(agent_code_hash),
            amount,
            memo,
            ctx=Context(
                accounts={
                    "payer": self.operator.pubkey(),
                    "usdc_mint": self.usdc_mint,
                    "payer_ata": payer_ata,
                    "agent_wallet_ata": agent_wallet_ata,
                    "wallet_program": self.programs.wallet,
                    "token_program": TOKEN_PROGRAM_ID,
                },
            ),
        )
        return await self.send_instruction(ix)

    async def deposit_to_pool(self, amount: int) -> str:
        """Credit.deposit — LP-side deposit. Operator acts as the LP here."""
        pool, _ = self.pool_pda()
        # Per IDL: ("deposit", lp) — one DepositRec per LP.
        deposit_rec, _ = Pubkey.find_program_address(
            [b"deposit", bytes(self.operator.pubkey())], self.programs.credit
        )
        pool_usdc = derive_ata(pool, self.usdc_mint)
        lp_usdc = derive_ata(self.operator.pubkey(), self.usdc_mint)
        ix = self.credit_program.instruction["deposit"](
            amount,
            ctx=Context(
                accounts={
                    "pool": pool,
                    "deposit": deposit_rec,
                    "lp": self.operator.pubkey(),
                    "lp_usdc": lp_usdc,
                    "pool_usdc": pool_usdc,
                    "usdc_mint": self.usdc_mint,
                    "token_program": TOKEN_PROGRAM_ID,
                    "system_program": SYSTEM_PROGRAM_ID,
                },
            ),
        )
        return await self.send_instruction(ix)

    async def withdraw_from_pool(self, shares: int) -> str:
        """Credit.withdraw — burn shares for proportional USDC."""
        pool, _ = self.pool_pda()
        deposit_rec, _ = Pubkey.find_program_address(
            [b"deposit", bytes(self.operator.pubkey())], self.programs.credit
        )
        pool_usdc = derive_ata(pool, self.usdc_mint)
        lp_usdc = derive_ata(self.operator.pubkey(), self.usdc_mint)
        ix = self.credit_program.instruction["withdraw"](
            shares,
            ctx=Context(
                accounts={
                    "pool": pool,
                    "deposit": deposit_rec,
                    "lp": self.operator.pubkey(),
                    "lp_usdc": lp_usdc,
                    "pool_usdc": pool_usdc,
                    "usdc_mint": self.usdc_mint,
                    "token_program": TOKEN_PROGRAM_ID,
                },
            ),
        )
        return await self.send_instruction(ix)

    async def vouch(self, amount: int, agent_code_hash: Optional[bytes] = None) -> str:
        """Reputation.vouch — stake USDC in support of an agent. Operator stakes
        for `agent_code_hash` (defaults to this agent's own code_hash)."""
        ch = agent_code_hash if agent_code_hash is not None else self.code_hash
        vouch_pool, _ = Pubkey.find_program_address(
            [b"vouch", ch], self.programs.reputation
        )
        voucher, _ = self.voucher_pda(self.operator.pubkey(), code_hash=ch)
        rep_stats, _ = self.rep_stats_pda()
        staker_usdc = derive_ata(self.operator.pubkey(), self.usdc_mint)
        vouch_pool_usdc = derive_ata(vouch_pool, self.usdc_mint)
        ix = self.reputation_program.instruction["vouch"](
            bytes(ch),
            amount,
            ctx=Context(
                accounts={
                    "vouch_pool": vouch_pool,
                    "voucher": voucher,
                    "rep_stats": rep_stats,
                    "staker": self.operator.pubkey(),
                    "staker_usdc": staker_usdc,
                    "vouch_pool_usdc": vouch_pool_usdc,
                    "usdc_mint": self.usdc_mint,
                    "token_program": TOKEN_PROGRAM_ID,
                    "system_program": SYSTEM_PROGRAM_ID,
                },
            ),
        )
        return await self.send_instruction(ix)

    async def unvouch_request(self, agent_code_hash: Optional[bytes] = None) -> str:
        """Reputation.request_unvouch — start the 7-day cooldown."""
        ch = agent_code_hash if agent_code_hash is not None else self.code_hash
        voucher, _ = self.voucher_pda(self.operator.pubkey(), code_hash=ch)
        ix = self.reputation_program.instruction["request_unvouch"](
            bytes(ch),
            ctx=Context(
                accounts={
                    "voucher": voucher,
                    "staker": self.operator.pubkey(),
                },
            ),
        )
        return await self.send_instruction(ix)

    async def slash(self, code_hash: bytes, total_loss: int) -> str:
        """Reputation.slash — CPI-only, called by Credit. Exposed here for parity
        with the spec but agents shouldn't normally call this directly; the
        Credit program invokes it inside `mark_default`."""
        vouch_pool, _ = Pubkey.find_program_address(
            [b"vouch", code_hash], self.programs.reputation
        )
        rep_stats, _ = self.rep_stats_pda()
        pool, _ = self.pool_pda()
        vouch_pool_usdc = derive_ata(vouch_pool, self.usdc_mint)
        lp_pool_usdc = derive_ata(pool, self.usdc_mint)
        # Burn ATA is owned by the all-zeros pubkey per the program docs.
        burn_owner = Pubkey.default()
        burn_usdc = derive_ata(burn_owner, self.usdc_mint)
        ix = self.reputation_program.instruction["slash"](
            bytes(code_hash),
            total_loss,
            ctx=Context(
                accounts={
                    "vouch_pool": vouch_pool,
                    "rep_stats": rep_stats,
                    "vouch_pool_usdc": vouch_pool_usdc,
                    "lp_pool_usdc": lp_pool_usdc,
                    "burn_usdc": burn_usdc,
                    "usdc_mint": self.usdc_mint,
                    "token_program": TOKEN_PROGRAM_ID,
                    "credit_program_signer": pool,  # credit Pool PDA is the gating signer
                },
            ),
        )
        return await self.send_instruction(ix)

    # ----- chain reads -----------------------------------------------------

    async def read_credit_line(self) -> Optional["CreditLineState"]:
        """Read & decode the agent's CreditLine PDA. Returns None if not opened."""
        pda, _ = self.credit_line_pda()
        client: AccountClient = self.credit_program.account["CreditLine"]
        try:
            raw = await client.fetch(pda, commitment=Confirmed)
        except Exception as exc:
            # anchorpy raises if the account doesn't exist or is the wrong type.
            log.debug("read_credit_line: %s", exc)
            return None
        return CreditLineState(
            principal=int(raw.principal),
            accrued_interest=int(raw.accrued_interest),
            apr_bps=int(raw.apr_bps),
            last_accrual=int(raw.last_accrual),
            is_active=bool(raw.is_active),
            agent_wallet_pda=raw.agent_wallet_pda,
        )

    async def read_vouch_pool_total(self) -> int:
        """Total staked on this agent's VouchPool. 0 if not initialised."""
        pda, _ = self.vouch_pool_pda()
        client: AccountClient = self.reputation_program.account["VouchPool"]
        try:
            raw = await client.fetch(pda, commitment=Confirmed)
        except Exception:
            return 0
        return int(raw.total_staked)

    async def read_max_vouch_pool_across_agents(self) -> int:
        """Return ``RepStats.max_total_staked_seen``.

        With the IDL we no longer need to sweep every VouchPool — the
        reputation program already tracks the running maximum in its global
        ``RepStats`` PDA, which is the on-chain denominator for the score.
        """
        pda, _ = self.rep_stats_pda()
        client: AccountClient = self.reputation_program.account["RepStats"]
        try:
            raw = await client.fetch(pda, commitment=Confirmed)
        except Exception as exc:
            log.warning("read_max_vouch_pool: RepStats not initialised (%s)", exc)
            return await self.read_vouch_pool_total()
        return int(raw.max_total_staked_seen)

    async def reputation_score(self) -> float:
        """Reputation score in [0.0, 1.0]. Matches the on-chain `compute_score`
        formula (own / max_seen, capped at 1.0)."""
        own = await self.read_vouch_pool_total()
        if own == 0:
            return 0.0
        peak = await self.read_max_vouch_pool_across_agents()
        if peak == 0:
            return 0.0
        return min(1.0, own / peak)

    # ----- payment verification --------------------------------------------

    async def has_recent_payment(self, payment_id: str) -> bool:
        """Return True iff a PaymentReceived event with this payment_id has been
        observed within `payment_validity_seconds`."""
        async with self._cache_lock:
            rec = self._payment_cache.get(payment_id)
            if rec is None:
                return False
            age = time.time() - rec.timestamp
            if age > self.payment_validity_seconds:
                # Lazy GC.
                del self._payment_cache[payment_id]
                return False
            return True

    async def consume_payment(self, payment_id: str) -> Optional[PaymentRecord]:
        """Atomically lookup + remove a payment record. Used by /summarize so
        the same payment cannot be redeemed twice."""
        async with self._cache_lock:
            return self._payment_cache.pop(payment_id, None)

    async def _record_payment(self, rec: PaymentRecord) -> None:
        async with self._cache_lock:
            self._payment_cache[rec.payment_id] = rec
            # Bound the cache: drop entries older than 2x the validity window.
            cutoff = time.time() - 2 * self.payment_validity_seconds
            stale = [k for k, v in self._payment_cache.items() if v.timestamp < cutoff]
            for k in stale:
                del self._payment_cache[k]

    # ----- payment event subscription --------------------------------------

    async def start_payment_subscriber(self) -> None:
        """Spawn a background task that subscribes to x402 logs and decodes
        PaymentReceived events via the IDL-driven event parser."""
        if self._ws_task is not None:
            return
        self._ws_task = asyncio.create_task(self._payment_subscriber_loop())

    async def _payment_subscriber_loop(self) -> None:
        try:
            from solana.rpc.websocket_api import connect as ws_connect
        except ImportError:
            log.error("solana websocket API unavailable; payment subscriber disabled")
            return

        backoff = 1.0
        while True:
            try:
                async with ws_connect(self.ws_url) as ws:
                    await ws.logs_subscribe(
                        {"mentions": [str(self.programs.x402)]},
                        commitment="confirmed",
                    )
                    backoff = 1.0
                    async for message in ws:
                        await self._handle_log_message(message)
            except asyncio.CancelledError:
                return
            except Exception as exc:
                log.warning("ws subscriber error: %s; retrying in %.1fs", exc, backoff)
                await asyncio.sleep(backoff)
                backoff = min(backoff * 2.0, 30.0)

    async def _handle_log_message(self, message: Any) -> None:
        """Parse a logs_subscribe message via the IDL event parser.

        anchorpy's ``EventParser.parse_logs`` understands the Anchor self-CPI
        log format (``Program data: <base64>``) and yields decoded events
        whose fields match the IDL types.
        """
        records: list[PaymentRecord] = []
        try:
            results = message if isinstance(message, list) else [message]
            for result in results:
                value = getattr(result, "result", None) or getattr(result, "value", None)
                if value is None:
                    continue
                logs = getattr(value, "logs", None) or []
                logs = [l for l in logs if isinstance(l, str)]
                if not logs:
                    continue

                # Collect records synchronously; awaitable cache writes happen
                # below so we never call asyncio inside the sync callback.
                self._x402_event_parser.parse_logs(
                    logs,
                    lambda ev: self._collect_payment_record(ev, records),
                )
        except Exception as exc:
            log.debug("log message handling failed: %s", exc)

        for rec in records:
            await self._record_payment(rec)
            log.info(
                "observed PaymentReceived payment_id=%s amount=%d",
                rec.payment_id,
                rec.amount,
            )

    def _collect_payment_record(self, event: Any, sink: list[PaymentRecord]) -> None:
        """Callback for `EventParser.parse_logs`. We're interested in
        ``PaymentReceived`` whose ``agent_code_hash`` matches us."""
        name = getattr(event, "name", None)
        if name != "PaymentReceived":
            return
        data = getattr(event, "data", None)
        if data is None:
            return
        # PaymentReceived fields per IDL: agent_code_hash, payer, amount, memo,
        # timestamp, slot, payment_id. The `payment_id` is the deterministic
        # hash the program emits; `memo` is the optional client-supplied tag
        # (we use that as the off-chain join key per spec).
        agent_ch = getattr(data, "agent_code_hash", None)
        if agent_ch is None or bytes(agent_ch) != bytes(self.code_hash):
            return
        memo = getattr(data, "memo", None)
        if memo is None:
            return
        amount = int(getattr(data, "amount", 0))
        payer = getattr(data, "payer", None)
        sink.append(
            PaymentRecord(
                payment_id=memo,
                payer=str(payer),
                amount=amount,
                memo=memo,
                timestamp=time.time(),
            )
        )


# ---------- account-state dataclasses --------------------------------------
#
# These are thin views over the IDL-decoded account records. We keep them as
# dataclasses (rather than passing the raw `Container` objects around) so the
# managers' type hints stay clean.


@dataclasses.dataclass
class CreditLineState:
    principal: int
    accrued_interest: int
    apr_bps: int
    last_accrual: int
    is_active: bool
    agent_wallet_pda: Pubkey

    @property
    def total_debt(self) -> int:
        return self.principal + self.accrued_interest


# ---------- env helpers -----------------------------------------------------


def _load_keypair(path: str) -> Keypair:
    """Load a Solana CLI–format keypair file (JSON array of 64 ints)."""
    import json as _json

    raw = _json.loads(Path(path).expanduser().read_text())
    if not isinstance(raw, list) or len(raw) not in (64, 65):
        raise ValueError(f"unexpected keypair format at {path}")
    return Keypair.from_bytes(bytes(raw[:64]))


def _derive_ws_url(rpc_url: str) -> str:
    if rpc_url.startswith("https://"):
        return "wss://" + rpc_url[len("https://"):]
    if rpc_url.startswith("http://"):
        return "ws://" + rpc_url[len("http://"):]
    return rpc_url
